export const dailyQuotes = [
  { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { quote: "The best way to predict the future is to create it.", author: "Peter Drucker" },
  { quote: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { quote: "Happiness depends upon ourselves.", author: "Aristotle" },
  { quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { quote: "Success is not final, failure is not fatal.", author: "Winston Churchill" },
  { quote: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { quote: "Everything you can imagine is real.", author: "Pablo Picasso" },
  { quote: "Stay hungry, stay foolish.", author: "Steve Jobs" },
  { quote: "Act as if what you do makes a difference.", author: "William James" },
  { quote: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { quote: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { quote: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  { quote: "Be yourself; everyone else is taken.", author: "Oscar Wilde" },
  { quote: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { quote: "What we think, we become.", author: "Buddha" },
  { quote: "Start where you are. Use what you have.", author: "Arthur Ashe" },
  { quote: "You become what you believe.", author: "Oprah Winfrey" },
  { quote: "Everything has beauty, but not everyone sees it.", author: "Confucius" },
  { quote: "The only limit is your mind.", author: "Napoleon Hill" },
  { quote: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { quote: "Try not to become a person of success, but of value.", author: "Albert Einstein" },
  { quote: "Don't count the days, make the days count.", author: "Muhammad Ali" },
  { quote: "Believe in yourself and all that you are.", author: "Christian D. Larson" },
  { quote: "If opportunity doesn't knock, build a door.", author: "Milton Berle" },
  { quote: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
  { quote: "Life is trying things to see if they work.", author: "Ray Bradbury" },
  { quote: "With the new day comes new strength.", author: "Eleanor Roosevelt" },
  { quote: "Success usually comes to those who are too busy to look for it.", author: "Henry David Thoreau" },
  { quote: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
  { quote: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { quote: "You are stronger than you think.", author: "A. A. Milne" },
  { quote: "The future belongs to those who prepare today.", author: "Malcolm X" },
  { quote: "Nothing will work unless you do.", author: "Maya Angelou" },
  { quote: "If you want to lift yourself up, lift someone else.", author: "Booker T. Washington" },
  { quote: "The power of imagination makes us infinite.", author: "John Muir" },
  { quote: "Go confidently in the direction of your dreams.", author: "Henry David Thoreau" },
  { quote: "The best revenge is massive success.", author: "Frank Sinatra" },
  { quote: "You define your own life.", author: "Michelle Obama" },
  { quote: "Light tomorrow with today.", author: "Elizabeth Barrett Browning" },
  { quote: "Wherever you go, go with all your heart.", author: "Confucius" },
  { quote: "Believe in your infinite potential.", author: "Roy T. Bennett" },
  { quote: "Don't wait. The time will never be just right.", author: "Napoleon Hill" },
  { quote: "You are enough just as you are.", author: "Meghan Markle" },
  { quote: "If you can dream it, you can do it.", author: "Walt Disney" },
  { quote: "Success is liking yourself.", author: "Maya Angelou" },
  { quote: "Make each day your masterpiece.", author: "John Wooden" },
  { quote: "Believe and act as if it were impossible to fail.", author: "Charles Kettering" },
  { quote: "Keep your face always toward the sunshine.", author: "Helen Keller" },
  { quote: "Do what you feel in your heart to be right.", author: "Eleanor Roosevelt" },
  { quote: "Happiness is not something ready-made.", author: "Dalai Lama" },
  { quote: "What lies behind us and before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { quote: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown Jr." },
  { quote: "You must be the change you wish to see.", author: "Mahatma Gandhi" },
  { quote: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
  { quote: "No pressure, no diamonds.", author: "Thomas Carlyle" },
  { quote: "Go as far as you can see; when you get there, you'll see further.", author: "J. P. Morgan" },
  { quote: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { quote: "Act like it is impossible to fail.", author: "Dorothea Brande" },
  { quote: "If you change the way you look at things, the things you look at change.", author: "Wayne Dyer" },
  { quote: "Life is either a daring adventure or nothing.", author: "Helen Keller" },
  { quote: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
  { quote: "You don't have to be great to start.", author: "Zig Ziglar" },
  { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { quote: "Do not wait for leaders; do it alone.", author: "Mother Teresa" },
  { quote: "The mind is everything. What you think you become.", author: "Buddha" },
  { quote: "Don't be pushed by your problems.", author: "Ralph Waldo Emerson" },
  { quote: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
  { quote: "Strive not to be a success, but to be of value.", author: "Albert Einstein" },
  { quote: "The harder the battle, the sweeter the victory.", author: "Les Brown" },
  { quote: "Nothing is impossible; the word itself says 'I'm possible.'", author: "Audrey Hepburn" },
  { quote: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { quote: "You can't use up creativity. The more you use, the more you have.", author: "Maya Angelou" },
  { quote: "Aim for the moon. If you miss, you may hit a star.", author: "W. Clement Stone" },
  { quote: "Don't limit yourself.", author: "Mary Kay Ash" },
  { quote: "The future starts today, not tomorrow.", author: "Pope John Paul II" },
  { quote: "Keep your eyes on the stars, and your feet on the ground.", author: "Theodore Roosevelt" },
  { quote: "With confidence, you have won before you have started.", author: "Marcus Garvey" },
  { quote: "The best time for new beginnings is now.", author: "Unknown" },
  { quote: "Do what you love, and you'll never work a day in your life.", author: "Marc Anthony" },
  { quote: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
  { quote: "Be so good they can't ignore you.", author: "Steve Martin" },
  { quote: "Courage is grace under pressure.", author: "Ernest Hemingway" },
  { quote: "Do something wonderful; people may imitate it.", author: "Albert Schweitzer" },
  { quote: "Everything you are is enough.", author: "Haemin Sunim" },
  { quote: "Your time is limited, so don't waste it.", author: "Steve Jobs" },
  { quote: "When you have a dream, you've got to grab it.", author: "Carol Burnett" },
  { quote: "Believe you deserve it and the universe will serve it.", author: "Gabrielle Bernstein" },
  { quote: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
  { quote: "Every moment is a fresh beginning.", author: "T.S. Eliot" },
  { quote: "Difficult roads often lead to beautiful destinations.", author: "Zig Ziglar" },
  { quote: "Your limitation is only your imagination.", author: "Unknown" },
  { quote: "Great things never come from comfort zones.", author: "Unknown" },
  { quote: "Dream it. Wish it. Do it.", author: "Unknown" },
  { quote: "Success doesn't just find you. You have to go out and get it.", author: "Unknown" },
  { quote: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown" },
  { quote: "Don't stop when you're tired. Stop when you're done.", author: "Unknown" },
  { quote: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
  { quote: "Little things make big days.", author: "Unknown" },
]

export function getDailyQuote(): { quote: string; author: string } {
  const today = new Date()
  const startOfYear = new Date(today.getFullYear(), 0, 0)
  const diff = today.getTime() - startOfYear.getTime()
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24))
  const quoteIndex = dayOfYear % dailyQuotes.length
  return dailyQuotes[quoteIndex]
}
